version: "2"

output:
  formats:
    text:
      path: stderr

linters:
  default: all
  disable:
    # These are linters we'd like to enable, but that will be labor intensive to
    # make existing code compliant.
    - wrapcheck
    - varnamelen
    - testpackage
    - paralleltest
    - nilnil
    - funcorder

    # These linters add whitespace in an attempt to make code more readable.
    - wsl
    - wsl_v5
    - nlreturn

    # Warns about uses of fmt.Sprintf that are less performant than alternatives.
    - perfsprint

    # Overly strict error handling requirements.
    - err113

    # These linters duplicate gocognit, but calculate complexity differently.
    - gocyclo
    - cyclop
    - nestif
    - funlen
    - maintidx

    # Enforces max line length. It's not idiomatic to enforce a strict limit.
    - lll

    # Warns about struct instantiations that don't specify every field.
    - exhaustruct

    # Warns about TODO comments.
    - godox

    # Warns about duplicated code blocks.
    - dupl

    # Warns about returning interfaces rather than concrete types.
    - ireturn

    # Warns about returning named variables.
    - nonamedreturns

    # Warns about using magic numbers.
    - mnd

    # Warns about if err := Foo(); err != nil style error checks.
    - noinlineerr

    # We need replace directives during development for unreleased dependencies.
    - gomoddirectives

  settings:
    depguard:
      rules:
        no_third_party_test_libraries:
          list-mode: lax
          files:
            - $test
          deny:
            - pkg: github.com/stretchr/testify
              desc: See https://go.dev/wiki/TestComments#assert-libraries
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    govet:
      disable:
        - shadow
    interfacebloat:
      max: 5
    nakedret:
      max-func-lines: 30
    nolintlint:
      require-explanation: true
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
    unused:
      exported-fields-are-used: true

  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
          - errcheck
          - forcetypeassert
          - gochecknoglobals
          - gochecknoinits
          - gocognit
          - gosec
          - unparam
        path: _test(ing)?\.go

      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)

      - linters:
          - gocritic
        text: "(hugeParam|rangeValCopy):"

      - linters:
          - staticcheck
        text: "SA3000:"

      - linters:
          - gosec
        text: "G101:"

      - linters:
          - gosec
        text: "G104:"

      - linters:
          - gosec
        text: "G601:"

    paths:
      - zz_generated\..+\.go$
      - .+\.pb.go$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crossplane)
        - blank
        - dot
      custom-order: true
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - zz_generated\..+\.go$
      - .+\.pb.go$
